/**
 * DashboardLayout - Main container for analytics dashboard
 * Features: Tab navigation, date range selection, export functionality
 */

import React, { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { toast } from '@/components/ui/use-toast';
import {
  BarChart3,
  TrendingUp,
  Activity,
  Download,
  Calendar,
  Share2
} from 'lucide-react';
import { calculateKeyMetrics, formatMinutesToHours } from '@/lib/analytics';

// Import Overview components
import { StatsGrid } from './overview/StatsGrid';
import { CompletionTrendChart } from './overview/CompletionTrendChart';
import { CategoryBreakdown } from './overview/CategoryBreakdown';

// Import Activities components
import { ActivityLeaderboard } from './activities/ActivityLeaderboard';
import { CategoryPerformance } from './activities/CategoryPerformance';
import { TimeOfDayHeatmap } from './activities/TimeOfDayHeatmap';

// Import Trends components
import { StreakHistory } from './trends/StreakHistory';
import { WeekOverWeekComparison } from './trends/WeekOverWeekComparison';
import { PerformanceCalendar } from './trends/PerformanceCalendar';

// Type imports (matching index.tsx structure)
interface Activity {
  id: string;
  name: string;
  duration: number;
  startTime: number | null;
  color: string;
  icon: string;
  category: string;
  order?: number;
  isDefault?: boolean;
}

interface ActivityRecord {
  completed: boolean;
  planned: boolean;
  actualDuration: number;
  completedAt: string | null;
  focusRating: number | null;
  notes: string;
}

interface DailyRecord {
  date: string;
  activities: Record<string, ActivityRecord>;
  completionRate?: number;
  mood?: string;
}

interface Profile {
  id: string;
  name: string;
  type: string;
  avatar: string;
  created: string;
  activities: Record<string, Activity>;
  dailyRecords: Record<string, DailyRecord>;
  streaks: {
    current: number;
    best: number;
    perfectDays: number;
    lastUpdate: string;
  };
  achievements: any[];
  preferences: {
    completionGoal: number;
    workingHours: { start: string; end: string };
    breakReminders: boolean;
    weeklyGoal: number;
  };
}

interface DashboardLayoutProps {
  profile: Profile;
  onClose?: () => void;
}

export type DateRange = '7days' | '30days' | '90days' | 'custom';

export const DashboardLayout: React.FC<DashboardLayoutProps> = ({ profile, onClose }) => {
  const [activeTab, setActiveTab] = useState<string>('overview');
  const [dateRange, setDateRange] = useState<DateRange>('7days');
  const [customStartDate, setCustomStartDate] = useState<string>('');
  const [customEndDate, setCustomEndDate] = useState<string>('');

  const handleExport = async () => {
    const days = getDaysFromRange();
    const metrics = calculateKeyMetrics(profile, days);

    const exportText = `FocusFlow Analytics Dashboard
${profile.avatar} ${profile.name} - ${getRangeLabel()}

━━━━━━━━━━━━━━━━━━━━━━
📊 KEY METRICS
━━━━━━━━━━━━━━━━━━━━━━

⏱️  Total Focused Time: ${formatMinutesToHours(metrics.totalFocusedTime)}
🎯 Avg Completion Rate: ${metrics.averageCompletionRate.toFixed(1)}%
🔥 Current Streak: ${metrics.currentStreak} days
🏆 Best Streak: ${metrics.bestStreak} days
⭐ Perfect Days: ${metrics.perfectDays}
📅 Active Days: ${metrics.activeDays}/${days}
✅ Activities Completed: ${metrics.totalActivitiesCompleted}

${metrics.mostProductiveDay ? `📈 Most Productive: ${new Date(metrics.mostProductiveDay.date).toLocaleDateString()} (${metrics.mostProductiveDay.rate.toFixed(0)}%)` : ''}
${metrics.favoriteActivity ? `❤️  Favorite Activity: ${metrics.favoriteActivity.icon} ${metrics.favoriteActivity.name} (${metrics.favoriteActivity.count}x)` : ''}

━━━━━━━━━━━━━━━━━━━━━━
Generated by FocusFlow`;

    try {
      await navigator.clipboard.writeText(exportText);
      toast({
        title: "📋 Exported!",
        description: "Dashboard data copied to clipboard"
      });
    } catch (err) {
      toast({
        title: "Export failed",
        description: "Could not copy to clipboard",
        variant: "destructive"
      });
    }
  };

  const handleShare = async () => {
    const days = getDaysFromRange();
    const metrics = calculateKeyMetrics(profile, days);

    const shareText = `📊 FocusFlow Analytics

${profile.avatar} ${profile.name}
${getRangeLabel()}

⏱️  ${formatMinutesToHours(metrics.totalFocusedTime)} focused
🎯 ${metrics.averageCompletionRate.toFixed(0)}% completion
🔥 ${metrics.currentStreak} day streak
⭐ ${metrics.perfectDays} perfect days

#FocusFlow #Productivity`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'FocusFlow Analytics',
          text: shareText
        });
      } catch (err) {
        // User cancelled or error - fallback to clipboard
        if (err instanceof Error && err.name !== 'AbortError') {
          await navigator.clipboard.writeText(shareText);
          toast({
            title: "📋 Copied!",
            description: "Share text copied to clipboard"
          });
        }
      }
    } else {
      // Fallback for browsers without Web Share API
      await navigator.clipboard.writeText(shareText);
      toast({
        title: "📋 Copied!",
        description: "Share text copied to clipboard"
      });
    }
  };

  const getDaysFromRange = (): number => {
    switch (dateRange) {
      case '7days':
        return 7;
      case '30days':
        return 30;
      case '90days':
        return 90;
      case 'custom':
        // Calculate days between custom dates
        if (customStartDate && customEndDate) {
          const start = new Date(customStartDate);
          const end = new Date(customEndDate);
          const diffTime = Math.abs(end.getTime() - start.getTime());
          const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
          return diffDays + 1;
        }
        return 7;
      default:
        return 7;
    }
  };

  const getRangeLabel = (): string => {
    switch (dateRange) {
      case '7days':
        return 'Last 7 Days';
      case '30days':
        return 'Last 30 Days';
      case '90days':
        return 'Last 90 Days';
      case 'custom':
        return customStartDate && customEndDate
          ? `${customStartDate} to ${customEndDate}`
          : 'Custom Range';
      default:
        return 'Last 7 Days';
    }
  };

  return (
    <div className="w-full h-full flex flex-col bg-background relative">
      {/* Header */}
      <div className="border-b bg-card flex-shrink-0">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between px-3 md:px-6 py-3 md:py-4 gap-3">
          <div className="flex-shrink-0">
            <h2 className="text-xl md:text-2xl font-bold flex items-center gap-2">
              <BarChart3 className="h-5 w-5 md:h-6 md:w-6 text-primary" />
              <span className="truncate">Analytics Dashboard</span>
            </h2>
            <p className="text-xs md:text-sm text-muted-foreground mt-1 truncate">
              {profile.avatar} {profile.name} • {getRangeLabel()}
            </p>
          </div>

          <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-2">
            {/* Date Range Selector */}
            <div className="flex items-center gap-1 bg-background rounded-lg border p-1">
              <Button
                variant={dateRange === '7days' ? 'default' : 'ghost'}
                size="sm"
                onClick={() => setDateRange('7days')}
                className="flex-1 sm:flex-none text-xs px-2"
              >
                7D
              </Button>
              <Button
                variant={dateRange === '30days' ? 'default' : 'ghost'}
                size="sm"
                onClick={() => setDateRange('30days')}
                className="flex-1 sm:flex-none text-xs px-2"
              >
                30D
              </Button>
              <Button
                variant={dateRange === '90days' ? 'default' : 'ghost'}
                size="sm"
                onClick={() => setDateRange('90days')}
                className="flex-1 sm:flex-none text-xs px-2"
              >
                90D
              </Button>
              <Button
                variant={dateRange === 'custom' ? 'default' : 'ghost'}
                size="sm"
                onClick={() => setDateRange('custom')}
                className="flex-1 sm:flex-none px-2"
              >
                <Calendar className="h-3 w-3 md:h-4 md:w-4" />
              </Button>
            </div>

            {/* Action Buttons */}
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" onClick={handleShare} className="flex-1 sm:flex-none text-xs">
                <Share2 className="h-3 w-3 md:h-4 md:w-4 mr-1 md:mr-2" />
                <span className="hidden sm:inline">Share</span>
              </Button>
              <Button variant="outline" size="sm" onClick={handleExport} className="flex-1 sm:flex-none text-xs">
                <Download className="h-3 w-3 md:h-4 md:w-4 mr-1 md:mr-2" />
                <span className="hidden sm:inline">Export</span>
              </Button>
            </div>
          </div>
        </div>

        {/* Custom Date Range Picker (if selected) */}
        {dateRange === 'custom' && (
          <div className="px-3 md:px-6 pb-3 md:pb-4 flex flex-col sm:flex-row items-stretch sm:items-center gap-3 sm:gap-4">
            <div className="flex items-center gap-2">
              <label className="text-xs md:text-sm font-medium whitespace-nowrap">From:</label>
              <input
                type="date"
                value={customStartDate}
                onChange={(e) => setCustomStartDate(e.target.value)}
                className="flex-1 px-2 md:px-3 py-1 border rounded-md text-xs md:text-sm"
              />
            </div>
            <div className="flex items-center gap-2">
              <label className="text-xs md:text-sm font-medium whitespace-nowrap">To:</label>
              <input
                type="date"
                value={customEndDate}
                onChange={(e) => setCustomEndDate(e.target.value)}
                className="flex-1 px-2 md:px-3 py-1 border rounded-md text-xs md:text-sm"
              />
            </div>
          </div>
        )}
      </div>

      {/* Tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab} className="flex-1 flex flex-col min-h-0">
        {/* Tab Navigation */}
        <div className="border-b bg-card px-3 md:px-6 flex-shrink-0">
          <TabsList className="bg-transparent border-b-0 w-full justify-start">
            <TabsTrigger
              value="overview"
              className="data-[state=active]:border-b-2 data-[state=active]:border-primary rounded-none text-xs md:text-sm flex-1 sm:flex-none"
            >
              <TrendingUp className="h-3 w-3 md:h-4 md:w-4 mr-1 md:mr-2" />
              <span className="hidden sm:inline">Overview</span>
              <span className="sm:hidden">Over.</span>
            </TabsTrigger>
            <TabsTrigger
              value="activities"
              className="data-[state=active]:border-b-2 data-[state=active]:border-primary rounded-none text-xs md:text-sm flex-1 sm:flex-none"
            >
              <Activity className="h-3 w-3 md:h-4 md:w-4 mr-1 md:mr-2" />
              <span className="hidden sm:inline">Activities</span>
              <span className="sm:hidden">Acts.</span>
            </TabsTrigger>
            <TabsTrigger
              value="trends"
              className="data-[state=active]:border-b-2 data-[state=active]:border-primary rounded-none text-xs md:text-sm flex-1 sm:flex-none"
            >
              <BarChart3 className="h-3 w-3 md:h-4 md:w-4 mr-1 md:mr-2" />
              <span className="hidden sm:inline">Trends</span>
              <span className="sm:hidden">Trend</span>
            </TabsTrigger>
          </TabsList>
        </div>

        {/* Tab Content Area - Scrollable */}
        <div className="flex-1 min-h-0 relative">
          <div className="absolute inset-0 overflow-hidden">
            {/* Overview Tab */}
            <TabsContent value="overview" className="h-full mt-0 overflow-y-auto overflow-x-hidden" style={{ WebkitOverflowScrolling: 'touch' }}>
              <div className="p-3 md:p-6">
                <OverviewTab profile={profile} days={getDaysFromRange()} />
              </div>
            </TabsContent>

            {/* Activities Tab */}
            <TabsContent value="activities" className="h-full mt-0 overflow-y-auto overflow-x-hidden" style={{ WebkitOverflowScrolling: 'touch' }}>
              <div className="p-3 md:p-6">
                <ActivitiesTab profile={profile} days={getDaysFromRange()} />
              </div>
            </TabsContent>

            {/* Trends Tab */}
            <TabsContent value="trends" className="h-full mt-0 overflow-y-auto overflow-x-hidden" style={{ WebkitOverflowScrolling: 'touch' }}>
              <div className="p-3 md:p-6">
                <TrendsTab profile={profile} days={getDaysFromRange()} />
              </div>
            </TabsContent>
          </div>
        </div>
      </Tabs>
    </div>
  );
};

// --- Tab Components ---

const OverviewTab: React.FC<{ profile: Profile; days: number }> = ({ profile, days }) => {
  return (
    <div className="space-y-4 md:space-y-6">
      {/* Key Metrics Cards */}
      <StatsGrid profile={profile} days={days} />

      {/* Charts Row */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-3 md:gap-6">
        <CompletionTrendChart profile={profile} days={days} />
        <CategoryBreakdown profile={profile} days={days} />
      </div>
    </div>
  );
};

const ActivitiesTab: React.FC<{ profile: Profile; days: number }> = ({ profile, days }) => {
  return (
    <div className="space-y-4 md:space-y-6">
      {/* Activity Leaderboard */}
      <ActivityLeaderboard profile={profile} days={days} />

      {/* Charts Row */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-3 md:gap-6">
        <CategoryPerformance profile={profile} days={days} />
        <TimeOfDayHeatmap profile={profile} days={days} />
      </div>
    </div>
  );
};

const TrendsTab: React.FC<{ profile: Profile; days: number }> = ({ profile, days }) => {
  return (
    <div className="space-y-4 md:space-y-6">
      {/* Week Comparison */}
      <WeekOverWeekComparison profile={profile} />

      {/* Charts Row */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-3 md:gap-6">
        <StreakHistory profile={profile} days={days} />
        <PerformanceCalendar profile={profile} days={days} />
      </div>
    </div>
  );
};

export default DashboardLayout;
